//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeNameSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeNameSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Возраст.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Жив.
        /// </summary>
        internal static string Alive {
            get {
                return ResourceManager.GetString("Alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a теперь лучшие друзья.
        /// </summary>
        internal static string BestFriends {
            get {
                return ResourceManager.GetString("BestFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a приезжает в город.
        /// </summary>
        internal static string ComeToTown {
            get {
                return ResourceManager.GetString("ComeToTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a и.
        /// </summary>
        internal static string Conjunction {
            get {
                return ResourceManager.GetString("Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a б,в,г,д,ж,з,к,л,м,н,п,р,с,т,й,х,ш.
        /// </summary>
        internal static string Consonants {
            get {
                return ResourceManager.GetString("Consonants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Умерло.
        /// </summary>
        internal static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a недолюбливают друг друга.
        /// </summary>
        internal static string Disobedient {
            get {
                return ResourceManager.GetString("Disobedient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a умирает.
        /// </summary>
        internal static string Dying {
            get {
                return ResourceManager.GetString("Dying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a теперь враждуют.
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a теперь друзья.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Пол.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a знакомится с.
        /// </summary>
        internal static string Meet {
            get {
                return ResourceManager.GetString("Meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Сбережения.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Приехало.
        /// </summary>
        internal static string Newcomers {
            get {
                return ResourceManager.GetString("Newcomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Население.
        /// </summary>
        internal static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a а,е,и,о,у,э,я.
        /// </summary>
        internal static string Vowels {
            get {
                return ResourceManager.GetString("Vowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Начать новую игру? (1 - да, 2 - нет - загрузить сохраненную.
        /// </summary>
        internal static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Год.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
